import 'package:flutter/material.dart';
import './models/country.dart';
import './models/continent.dart';

const getContinents = const [
  Continent(
    id: "0",
    name: "Asia",
    color: Colors.purpleAccent,
    image: "assets/images/asia.png",
  ),
  Continent(
    id: "1",
    name: "Africa",
    color: Colors.redAccent,
    image: "assets/images/africa.png",
  ),
  Continent(
    id: "2",
    name: "Antarctica",
    color: Colors.indigo,
    image: "assets/images/antarctica.png",
  ),
  Continent(
    id: "3",
    name: "Australia",
    color: Colors.deepOrange,
    image: "assets/images/australia.png",
  ),
  Continent(
    id: "4",
    name: "Europe",
    color: Colors.teal,
    image: "assets/images/europe.png",
  ),
  Continent(
    id: "5",
    name: "North America",
    color: Colors.brown,
    image: "assets/images/north_america.png",
  ),
  Continent(
    id: "6",
    name: "South America",
    color: Colors.green,
    image: "assets/images/south_america.png",
  ),
];

const getContries = const [
  Country(
    continentId: "0",
    name: "Afghanistan",
    image: "assets/images/asia/Afghanistan.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Afghanistan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Armenia",
    image: "assets/images/asia/Armenia.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Armenia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Azerbaijan",
    image: "assets/images/asia/Azerbaijan.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Azerbaijan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Bahrain",
    image: "assets/images/asia/Bahrain.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Bahrain.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Bangladesh",
    image: "assets/images/asia/Bangladesh.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Bangladesh.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Bhutan",
    image: "assets/images/asia/Bhutan.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Bhutan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Brunei",
    image: "assets/images/asia/Brunei.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Brunei.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Cambodia",
    image: "assets/images/asia/Cambodia.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Cambodia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "China",
    image: "assets/images/asia/China.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/China.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Cyprus",
    image: "assets/images/asia/Cyprus.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Cyprus.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Georgia",
    image: "assets/images/asia/Georgia.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Georgia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "India",
    image: "assets/images/asia/India.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/India.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Indonesia",
    image: "assets/images/asia/Indonesia.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Indonesia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Iran",
    image: "assets/images/asia/Iran.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Iran.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Iraq",
    image: "assets/images/asia/Iraq.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Iraq.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Israel",
    image: "assets/images/asia/Israel.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Israel.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Japan",
    image: "assets/images/asia/Japan.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Japan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Jordan",
    image: "assets/images/asia/Jordan.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Jordan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Kazakhstan",
    image: "assets/images/asia/Kazakhstan.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Kazakhstan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Kuwait",
    image: "assets/images/asia/Kuwait.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Kuwait.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Kyrgyzstan",
    image: "assets/images/asia/Kyrgyzstan.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Kyrgyzstan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Laos",
    image: "assets/images/asia/Laos.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Laos.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Lebanon",
    image: "assets/images/asia/Lebanon.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Lebanon.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Malaysia",
    image: "assets/images/asia/Malaysia.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Malaysia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Maldives",
    image: "assets/images/asia/Maldives.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Maldives.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Mongolia",
    image: "assets/images/asia/Mongolia.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Mongolia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Myanmar",
    image: "assets/images/asia/Myanmar.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Myanmar.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Nepal",
    image: "assets/images/asia/Nepal.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Nepal.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "North_Korea",
    image: "assets/images/asia/North_Korea.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/North_Korea.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Oman",
    image: "assets/images/asia/Oman.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Oman.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Pakistan",
    image: "assets/images/asia/Pakistan.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Pakistan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Palestine",
    image: "assets/images/asia/Palestine.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Palestine.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Philippine",
    image: "assets/images/asia/Philippine.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Philippine.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Qatar",
    image: "assets/images/asia/Qatar.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Qatar.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Russia",
    image: "assets/images/asia/Russia.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Russia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Saudi_Arabia",
    image: "assets/images/asia/Saudi_Arabia.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Saudi_Arabia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Singapore",
    image: "assets/images/asia/Singapore.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Singapore.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "South_Korea",
    image: "assets/images/asia/South_Korea.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/South_Korea.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Sri_Lanka",
    image: "assets/images/asia/Sri_Lanka.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Sri_Lanka.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Syria",
    image: "assets/images/asia/Syria.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Syria.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Taiwan",
    image: "assets/images/asia/Taiwan.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Taiwan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Tajikistan",
    image: "assets/images/asia/Tajikistan.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Tajikistan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Thailand",
    image: "assets/images/asia/Thailand.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Thailand.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Timor-Leste",
    image: "assets/images/asia/Timor-Leste.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Timor-Leste.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Turkey",
    image: "assets/images/asia/Turkey.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Turkey.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Turkmenistan",
    image: "assets/images/asia/Turkmenistan.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Turkmenistan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "United_Arab_Emirates",
    image: "assets/images/asia/United_Arab_Emirates.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/United_Arab_Emirates.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Uzbekistan",
    image: "assets/images/asia/Uzbekistan.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Uzbekistan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Vietnam",
    image: "assets/images/asia/Vietnam.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Vietnam.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "0",
    name: "Yemen",
    image: "assets/images/asia/Yemen.png",
    linktoMaps: " ",
    geography: "assets/geofile/asia/Yemen.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Algeria",
    image: "assets/images/africa/Algeria.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Algeria.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Angola",
    image: "assets/images/africa/Angola.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Angola.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Benin",
    image: "assets/images/africa/Benin.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Benin.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Botswana",
    image: "assets/images/africa/Botswana.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Botswana.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Burkina_Faso",
    image: "assets/images/africa/Burkina_Faso.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Burkina_Faso.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Burundi",
    image: "assets/images/africa/Burundi.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Burundi.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Cabo_Verde",
    image: "assets/images/africa/Cabo_Verde.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Cabo_Verde.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Cameroon",
    image: "assets/images/africa/Cameroon.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Cameroon.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Central_African_Republic",
    image: "assets/images/africa/Central_African_Republic.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Central_African_Republic.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Chad",
    image: "assets/images/africa/Chad.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Chad.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Comoros",
    image: "assets/images/africa/Comoros.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Comoros.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Democratic_Republic_of_the_Congo",
    image: "assets/images/africa/Democratic_Republic_of_the_Congo.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Democratic_Republic_of_the_Congo.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Djibouti",
    image: "assets/images/africa/Djibouti.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Djibouti.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Egypt",
    image: "assets/images/africa/Egypt.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Egypt.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Equatorial_Guinea",
    image: "assets/images/africa/Equatorial_Guinea.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Equatorial_Guinea.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Eritrea",
    image: "assets/images/africa/Eritrea.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Eritrea.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Ethiopia",
    image: "assets/images/africa/Ethiopia.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Ethiopia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Gabon",
    image: "assets/images/africa/Gabon.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Gabon.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Gambia",
    image: "assets/images/africa/Gambia.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Gambia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Ghana",
    image: "assets/images/africa/Ghana.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Ghana.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Guinea-Bissau",
    image: "assets/images/africa/Guinea-Bissau.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Guinea-Bissau.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Guinea",
    image: "assets/images/africa/Guinea.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Guinea.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Ivory_Coast",
    image: "assets/images/africa/Ivory_Coast.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Ivory_Coast.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Kenya",
    image: "assets/images/africa/Kenya.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Kenya.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Lesotho",
    image: "assets/images/africa/Lesotho.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Lesotho.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Liberia",
    image: "assets/images/africa/Liberia.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Liberia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Libya",
    image: "assets/images/africa/Libya.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Libya.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Madagascar",
    image: "assets/images/africa/Madagascar.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Madagascar.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Malawi",
    image: "assets/images/africa/Malawi.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Malawi.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Mali",
    image: "assets/images/africa/Mali.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Mali.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Mauritania",
    image: "assets/images/africa/Mauritania.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Mauritania.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Mauritius",
    image: "assets/images/africa/Mauritius.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Mauritius.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Morocco",
    image: "assets/images/africa/Morocco.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Morocco.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Mozambique",
    image: "assets/images/africa/Mozambique.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Mozambique.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Namibia",
    image: "assets/images/africa/Namibia.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Namibia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Niger",
    image: "assets/images/africa/Niger.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Niger.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Nigeria",
    image: "assets/images/africa/Nigeria.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Nigeria.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Republic_of_the_Congo",
    image: "assets/images/africa/Republic_of_the_Congo.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Republic_of_the_Congo.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Rwanda",
    image: "assets/images/africa/Rwanda.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Rwanda.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Sao_Tome_and_Principe",
    image: "assets/images/africa/Sao_Tome_and_Principe.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Sao_Tome_and_Principe.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Senegal",
    image: "assets/images/africa/Senegal.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Senegal.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Seychelles",
    image: "assets/images/africa/Seychelles.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Seychelles.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Sierra_Leone",
    image: "assets/images/africa/Sierra_Leone.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Sierra_Leone.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Somalia",
    image: "assets/images/africa/Somalia.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Somalia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "South_Africa",
    image: "assets/images/africa/South_Africa.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/South_Africa.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "South_Sudan",
    image: "assets/images/africa/South_Sudan.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/South_Sudan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Sudan",
    image: "assets/images/africa/Sudan.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Sudan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Swaziland",
    image: "assets/images/africa/Swaziland.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Swaziland.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Tanzania",
    image: "assets/images/africa/Tanzania.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Tanzania.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Togo",
    image: "assets/images/africa/Togo.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Togo.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Tunisia",
    image: "assets/images/africa/Tunisia.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Tunisia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Uganda",
    image: "assets/images/africa/Uganda.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Uganda.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Zambia",
    image: "assets/images/africa/Zambia.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Zambia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "1",
    name: "Zimbabwe",
    image: "assets/images/africa/Zimbabwe.png",
    linktoMaps: " ",
    geography: "assets/geofile/africa/Zimbabwe.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "Australia",
    image: "assets/images/australia/Australia.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/Australia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "Federated_States_of_Micronesia",
    image: "assets/images/australia/Federated_States_of_Micronesia.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/Federated_States_of_Micronesia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "Fiji",
    image: "assets/images/australia/Fiji.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/Fiji.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "Kiribati",
    image: "assets/images/australia/Kiribati.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/Kiribati.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "Marshall_Islands",
    image: "assets/images/australia/Marshall_Islands.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/Marshall_Islands.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "Nauru",
    image: "assets/images/australia/Nauru.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/Nauru.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "New_Zealand",
    image: "assets/images/australia/New_Zealand.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/New_Zealand.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "Palau",
    image: "assets/images/australia/Palau.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/Palau.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "Papua_New_Guinea",
    image: "assets/images/australia/Papua_New_Guinea.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/Papua_New_Guinea.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "Samoa",
    image: "assets/images/australia/Samoa.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/Samoa.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "Solomon_Islands",
    image: "assets/images/australia/Solomon_Islands.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/Solomon_Islands.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "Tonga",
    image: "assets/images/australia/Tonga.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/Tonga.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "Tuvalu",
    image: "assets/images/australia/Tuvalu.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/Tuvalu.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "3",
    name: "Vanuatu",
    image: "assets/images/australia/Vanuatu.png",
    linktoMaps: " ",
    geography: "assets/geofile/australia/Vanuatu.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Albania",
    image: "assets/images/europe/Albania.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Albania.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Andorra",
    image: "assets/images/europe/Andorra.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Andorra.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Armenia",
    image: "assets/images/europe/Armenia.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Armenia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Austria",
    image: "assets/images/europe/Austria.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Austria.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Azerbaijan",
    image: "assets/images/europe/Azerbaijan.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Azerbaijan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Belarus",
    image: "assets/images/europe/Belarus.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Belarus.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Belgium",
    image: "assets/images/europe/Belgium.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Belgium.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Bosnia_and_Herzegovina",
    image: "assets/images/europe/Bosnia_and_Herzegovina.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Bosnia_and_Herzegovina.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Bulgaria",
    image: "assets/images/europe/Bulgaria.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Bulgaria.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Croatia",
    image: "assets/images/europe/Croatia.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Croatia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Cyprus",
    image: "assets/images/europe/Cyprus.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Cyprus.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Czech_Republic",
    image: "assets/images/europe/Czech_Republic.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Czech_Republic.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Denmark",
    image: "assets/images/europe/Denmark.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Denmark.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Estonia",
    image: "assets/images/europe/Estonia.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Estonia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Finland",
    image: "assets/images/europe/Finland.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Finland.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "France",
    image: "assets/images/europe/France.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/France.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Georgia",
    image: "assets/images/europe/Georgia.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Georgia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Germany",
    image: "assets/images/europe/Germany.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Germany.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Greece",
    image: "assets/images/europe/Greece.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Greece.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Hungary",
    image: "assets/images/europe/Hungary.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Hungary.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Iceland",
    image: "assets/images/europe/Iceland.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Iceland.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Ireland",
    image: "assets/images/europe/Ireland.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Ireland.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Italy",
    image: "assets/images/europe/Italy.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Italy.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Kazakhstan",
    image: "assets/images/europe/Kazakhstan.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Kazakhstan.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Kosovo",
    image: "assets/images/europe/Kosovo.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Kosovo.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Latvia",
    image: "assets/images/europe/Latvia.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Latvia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Liechtenstein",
    image: "assets/images/europe/Liechtenstein.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Liechtenstein.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Lithuania",
    image: "assets/images/europe/Lithuania.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Lithuania.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Luxembourg",
    image: "assets/images/europe/Luxembourg.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Luxembourg.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Macedonia",
    image: "assets/images/europe/Macedonia.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Macedonia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Malta",
    image: "assets/images/europe/Malta.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Malta.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Moldova",
    image: "assets/images/europe/Moldova.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Moldova.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Monaco",
    image: "assets/images/europe/Monaco.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Monaco.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Montenegro",
    image: "assets/images/europe/Montenegro.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Montenegro.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Netherlands",
    image: "assets/images/europe/Netherlands.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Netherlands.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Norway",
    image: "assets/images/europe/Norway.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Norway.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Poland",
    image: "assets/images/europe/Poland.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Poland.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Portugal",
    image: "assets/images/europe/Portugal.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Portugal.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Romania",
    image: "assets/images/europe/Romania.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Romania.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Russia",
    image: "assets/images/europe/Russia.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Russia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "San_Marino",
    image: "assets/images/europe/San_Marino.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/San_Marino.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Serbia",
    image: "assets/images/europe/Serbia.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Serbia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Slovakia",
    image: "assets/images/europe/Slovakia.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Slovakia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Slovenia",
    image: "assets/images/europe/Slovenia.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Slovenia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Spain",
    image: "assets/images/europe/Spain.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Spain.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Sweden",
    image: "assets/images/europe/Sweden.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Sweden.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Switzerland",
    image: "assets/images/europe/Switzerland.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Switzerland.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Turkey",
    image: "assets/images/europe/Turkey.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Turkey.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Ukraine",
    image: "assets/images/europe/Ukraine.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Ukraine.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "United_Kingdom",
    image: "assets/images/europe/United_Kingdom.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/United_Kingdom.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "4",
    name: "Vatican_City",
    image: "assets/images/europe/Vatican_City.png",
    linktoMaps: " ",
    geography: "assets/geofile/europe/Vatican_City.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Antigua_and_Barbuda",
    image: "assets/images/north_america/Antigua_and_Barbuda.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Antigua_and_Barbuda.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Bahamas",
    image: "assets/images/north_america/Bahamas.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Bahamas.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Barbados",
    image: "assets/images/north_america/Barbados.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Barbados.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Belize",
    image: "assets/images/north_america/Belize.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Belize.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Canada",
    image: "assets/images/north_america/Canada.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Canada.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Costa_Rica",
    image: "assets/images/north_america/Costa_Rica.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Costa_Rica.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Cuba",
    image: "assets/images/north_america/Cuba.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Cuba.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Dominica",
    image: "assets/images/north_america/Dominica.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Dominica.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "El_Salvador",
    image: "assets/images/north_america/El_Salvador.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/El_Salvador.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Gabon",
    image: "assets/images/north_america/Gabon.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Gabon.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Grenada",
    image: "assets/images/north_america/Grenada.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Grenada.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Guatemala",
    image: "assets/images/north_america/Guatemala.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Guatemala.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Haiti",
    image: "assets/images/north_america/Haiti.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Haiti.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Honduras",
    image: "assets/images/north_america/Honduras.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Honduras.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Jamaica",
    image: "assets/images/north_america/Jamaica.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Jamaica.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Mexico",
    image: "assets/images/north_america/Mexico.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Mexico.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Nicaragua",
    image: "assets/images/north_america/Nicaragua.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Nicaragua.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Panama",
    image: "assets/images/north_america/Panama.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Panama.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Saint_Kitts_and_Nevis",
    image: "assets/images/north_america/Saint_Kitts_and_Nevis.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Saint_Kitts_and_Nevis.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Saint_Lucia",
    image: "assets/images/north_america/Saint_Lucia.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Saint_Lucia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Saint_Vincent_and_the_Grenadines",
    image: "assets/images/north_america/Saint_Vincent_and_the_Grenadines.png",
    linktoMaps: " ",
    geography:
        "assets/geofile/north_america/Saint_Vincent_and_the_Grenadines.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "Trinidad_and_Tobago",
    image: "assets/images/north_america/Trinidad_and_Tobago.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/Trinidad_and_Tobago.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "5",
    name: "United_States",
    image: "assets/images/north_america/United_States.png",
    linktoMaps: " ",
    geography: "assets/geofile/north_america/United_States.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "6",
    name: "Argentina",
    image: "assets/images/south_america/Argentina.png",
    linktoMaps: " ",
    geography: "assets/geofile/south_america/Argentina.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "6",
    name: "Bolivia",
    image: "assets/images/south_america/Bolivia.png",
    linktoMaps: " ",
    geography: "assets/geofile/south_america/Bolivia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "6",
    name: "Brazil",
    image: "assets/images/south_america/Brazil.png",
    linktoMaps: " ",
    geography: "assets/geofile/south_america/Brazil.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "6",
    name: "Chile",
    image: "assets/images/south_america/Chile.png",
    linktoMaps: " ",
    geography: "assets/geofile/south_america/Chile.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "6",
    name: "Colombia",
    image: "assets/images/south_america/Colombia.png",
    linktoMaps: " ",
    geography: "assets/geofile/south_america/Colombia.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "6",
    name: "Ecuador",
    image: "assets/images/south_america/Ecuador.png",
    linktoMaps: " ",
    geography: "assets/geofile/south_america/Ecuador.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "6",
    name: "Guyana",
    image: "assets/images/south_america/Guyana.png",
    linktoMaps: " ",
    geography: "assets/geofile/south_america/Guyana.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "6",
    name: "Paraguay",
    image: "assets/images/south_america/Paraguay.png",
    linktoMaps: " ",
    geography: "assets/geofile/south_america/Paraguay.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "6",
    name: "Peru",
    image: "assets/images/south_america/Peru.png",
    linktoMaps: " ",
    geography: "assets/geofile/south_america/Peru.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "6",
    name: "Suriname",
    image: "assets/images/south_america/Suriname.png",
    linktoMaps: " ",
    geography: "assets/geofile/south_america/Suriname.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "6",
    name: "Uruguay",
    image: "assets/images/south_america/Uruguay.png",
    linktoMaps: " ",
    geography: "assets/geofile/south_america/Uruguay.txt",
    areaImage: " ",
  ),
  Country(
    continentId: "6",
    name: "Venezuela",
    image: "assets/images/south_america/Venezuela.png",
    linktoMaps: " ",
    geography: "assets/geofile/south_america/Venezuela.txt",
    areaImage: " ",
  ),
];
